### ISSUE TITLE
Does not work anymore with org-mode 9.0

### ISSUE THREAD

**Issue by jeromg** [sprig/org-capture-extension#18]
It looks like the new-style links available in org-mode 9.0 break this extension.

I now receive the following warning in the *Warnings* buffer:
`Warning (emacs): Please update your org protocol handler to deal with new-style links.`

And the following message in *Messages*:
```
Greedy org-protocol handler.  Killing client.
No server buffers remain to edit
```

I have not changed my capture templates which are:
```
("p" "Protocol" entry (file+headline (concat org-directory "/bookmarks.org") "Inbox") "* %? [[%:link][%:description]] \n  - Captured: %U \n#+BEGIN_QUOTE\n%i\n#+END_QUOTE\n" :immediate-finish t)
("L" "Protocol Link" entry (file+headline (concat org-directory "/bookmarks.org") "Inbox") "* %? [[%:link][%:description]] \n  - Captured: %U" :immediate-finish t)

``` 
Thanks for your help.

**Comment by sprig** [comment]
According to http://orgmode.org/Changes.html#org8954d3c old style links continue to be supported, therefore the extension is supposed to continue working as-is (and it does, for me).

You need to do the investigative legwork.

0. Please describe your setup. Linux? Version. OSX? Version. Emacs? Version. Chrome? Version. How did you get your system to send org-protocol links to emacs?

1. Please find the simplest URL for which it fails (does it work on a simple address that contain only alphanumeric characters and periods? and backslashes? and query parameters? and escaped characters? etc.). Then open the developer console and look for the debug message that the extension gives and paste it here.

2. Open a terminal and run `$open "COPIED-URL"` (do not skip the quotes, unless what you are pasting already has quotes around it). $open is simply open if you are on OSX and xdg-open if on linux. COPIED-URL is obviously the url you pasted here in step 1. Does it work? Congrats, you found where the problem is not (i.e. inside chrome). No? Does `$open org-"protocol://capture:/p/a/b"` work? No? Again you found where the problem lies not. Otherwise proceed to step 3.

3. Call up the line you ran in the terminal with the non-working url. it will be of the form `open "org-protocol://capture:/<letter>/PIECE1/PIECE2/` with PIECE2 usually being longer and more complex if you selected any text, and PIECE1 otherwise. Please edit the url until it is as short as possible while still breaking (Note, % should always be proceeded by two digits/letters in the ranges 0-9 and A-F so do not leave a percent sign with a single symbol following). You can probably trim one of the pieces to be just one character. Paste here the smallest breaking URL.

3. Try sending said URL directly to emacsclient, for good measure. Does it work? Again, congrats. *If you are using OSX, make sure that the `emacsclient` which you call is the correct one!* 

P.S.
It is of course fine to ask about problems in your config. Just keep the distinction of extension is broken/your config is broken.

**Comment by jeromg** [comment]
Thanks a lot for the feedback and the troubleshooting steps, I'm quite new to emacs and I'm still struggling (also note I didn't blame the extension, I initially blamed org 9.0 ;).
I could reproduce with the simplest url (web site root, no parameters). So I ended up cleaning my .emacs.d folder and reinstalling all packages. That was apparently enough to fix the problem.
Thanks a lot again.

**Comment by sprig** [comment]
Sure thing! I used this as an opportunity to add troubleshooting
instructions to the readme :-)

**Comment by ghost** [comment]
The old-style links also seem to be not really working on my machine. Can this extension be updated?
