### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by jabranham** [sprig/org-capture-extension#20]
Hi - 

Just an FYI - your extension also works on Firefox. I've tested it on Firefox 51 (current stable release) and Firefox 53 (developer edition). Firefox users can use [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) to install it directly without any issues (though it requires a Firefox account). 

If you want to, you can upload it to Firefox's Add-ons page fairly easily. There's info on that process here: https://developer.mozilla.org/en-US/Add-ons/Distribution

Thanks for your work on this extension!

**Comment by sprig** [comment]
Thanks for the info! I think the main reason I did not investigate is that there is already another extension for Firefox. On the other hand, it wouldn't hurt to have a little competition so I'll add it as you suggest.

**Comment by jabranham** [comment]
Great, thanks! If you're talking about [this one](https://addons.mozilla.org/en-US/firefox/addon/org-mode-capture/) it will stop working in Firefox 57 (aurora in August; stable release in November) unless the dev updates it.

**Comment by sprig** [comment]
Good to know. So, I don't have the time right now to go through the documentation for how to properly make a Firefox extension, but I was hoping that Chrome Store Foxified (CSF) would be a way around that for the time being.

However, it turns out that the new project is registered as a private one (naturally). The problem is that I couldn't figure out how to make it a public one without bumping the version, and I would prefer not to (plus, I think there might be a problem with that, because CSF would also bump the private version, circumventing the workaround).

Do you have any advice? Maybe I missed the setting to turn the project public somewhere?

**Comment by jabranham** [comment]
I think that may be more complicated than just uploading it to AMO directly. All you need to do that is create a .zip file of the addon, sign into your account, upload it (and wait a second for Mozilla do some automatic checks), then tell them that you want it distributed on AMO. 

More info: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Publishing_your_WebExtension

**Comment by sprig** [comment]
You are right! Somehow the first time I tried, I received an error that seemed to indicate that I didn't have the appropriate manifest, but now it worked smoothly.

Since you used the chrome store foxified, is it possible that you captured the `org-capture' slug with your private submission? If so, would you mind changing it so that I can use it? Unless you plan to start a competing extension, of course :-)

Thanks in advance!

**Comment by jabranham** [comment]
OK, I've changed the name and URL so hopefully org capture is free for you!

**Comment by sprig** [comment]
Thanks!

If you want, you can install the official extension at https://addons.mozilla.org/en-US/firefox/addon/org-capture now :-)

**Comment by jabranham** [comment]
Awesome, thanks! 

PS - you may want to mention it at the top of the README :-)

**Comment by sprig** [comment]
Yes, of course - I just didn't get to that yet...
