### ISSUE TITLE
capture fails in one template, ok in another?

### ISSUE THREAD

**Issue by cryoguy** [sprig/org-capture-extension#23]
The capture works in this template:
` ("p" "Phone call" entry (file "refile.org")
      "* TODO CALL %? :PHONE:\n%U" :clock-in t :clock-resume t)`
But NOT in the following one (with error -No server buffers remain to edit):
` ("p" "Protocol" entry (file+headline ,(concat org-directory "ff-notes.org") "Inbox")
      "* %^{Title}\nSource: %u, %c\n#+BEGIN_QUOTE\n%i\n#+END_QUOTE\n%?")`
I am using Emacs 25.5, org-mode 9.0.5  Firefox 53.0 (64bit).

**Comment by sprig** [comment]
Maybe I am stating the obvious, but it appears to be a problem with the template.

It has been some time since I messed around with capture templates so I am wildly guessing here, but do you have a heading titled "Inbox" in the `ff-notes.org` file? and does the file actually exist? is  org-directory defined and pointing where you expect? 

Sorry I can't do much more than this, but please do write back with your findings to help others if they face a similar problem.

P.S.
I'm not sure if you haven't made a mistake in the emacs version, but if you are using a dev one, perhaps also try using a stable version?

**Comment by dinkonin** [comment]
Had the same problem on Emacs 25.2.1 (in Windows) fixed it by changing `nSource: %u, %c\n` to `nSource: %u, [[%:link]]\n`

**Comment by sprig** [comment]
Thanks for the tio @dinkonin !

**Comment by lkmokadam** [comment]
I am new to org-mode. I had the same problem. Googled and debugged for 2 hrs.  In the end, resolved it using this solution. I think this should be in the readme.
