### ISSUE TITLE
Brackets '[' ']' in link description cause broken org-mode link

### ISSUE THREAD

**Issue by vincent-picaud** [sprig/org-capture-extension#37]
Thank you for this great extension, it worked out of the box with my config (Debian distro).

I just had some problems with ArXiv.org links (https://arxiv.org/abs/1606.04838 for instance), because page tile: 

> [1606.04838] Optimization Methods for Large-Scale Machine Learning

contains [, ] brackets.

Using the org-capture-template:
```
(setq org-capture-templates `(
	
	("L" "Protocol Link" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
        "* %? [[%:link][%:description]]\n")
))
```

returns broken org-mode link. 

I used a function to convert [, ] char into (, ) to fix this:

```
(defun transform-square-brackets-to-round-ones(string-to-transform)
  "Transforms [ into ( and ] into ), other chars left unchanged."
  (concat 
  (mapcar #'(lambda (c) (if (equal c ?[) ?\( (if (equal c ?]) ?\) c))) string-to-transform))
  )

(setq org-capture-templates `(
	
	("L" "Protocol Link" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
        "* %? [[%:link][%(transform-square-brackets-to-round-ones \"%:description\")]]\n")
))
```

but I think that there is certainly better/more elegant fix.

Maybe it would be interesting to mention this potential problem in the doc (ArXiv is a widely used site)

Best,
Vincent

**Comment by sprig** [comment]
:-) Thanks for pointing this out!

I'm not sure there is a better solution than what you posted to be found - I believe the extension itself should send the data to emacs unmodified since various users could have different templates (i.e. the templates in the readme should be viewed as a starting point for further modification). I guess the original org link format was not designed to have links with square brackets in their descriptions.

I'll add your solution to the readme - in the future, feel free to create the PR :-)

**Comment by vincent-picaud** [comment]
I understand and do agree. Next time I will think of PR :-)
