### ISSUE TITLE
Use store-link instead of org-protocol://capture:/L

### ISSUE THREAD

**Issue by brunoqc** [sprig/org-capture-extension#4]
Did you know that you can use `store-link` with org-protocol?

It would be nice to use it (as default or maybe as an option). I could work on this feature.

```js
javascript:location.href='org-protocol://store-link://'+      encodeURIComponent(location.href)+'/'+      encodeURIComponent(document.title)+'/'+      encodeURIComponent(window.getSelection())
```

**Comment by sprig** [comment]
I did know. I found it more convenient to create a link note automatically rather than to store a link, since I found that what I do after storing a link is creating a note with the link...

Obviously, that would not suite everyone, but I also don't want to lose my use case. If you could create an options page it to customize what happens when one clicks, it could be great.

I imagine that if I did the page I would initially just let users customize the javascript snippet that gets run. Eventually - with more polish - I'd probably hide these under 'advanced' and just let people pick which handler they want.

**Comment by sprig** [comment]
Closing old discussion. Feel free to reopen.
