### ISSUE TITLE
No longer works. Opens new window.

### ISSUE THREAD

**Issue by bon** [sprig/org-capture-extension#5]
After working flawlessly for months, this no longer works on a recent Chromium version.

I have Chromium 46.0.2490.80 on Linux.

Now the extension opens a new Chromium window instead of sending the capture to emacs.

**Comment by sprig** [comment]
Hi bon,

It sounds as though something happened to the association of org-protocol to emacsclient.

Could you please paste:
``` org-protocol://capture:/p/foo/bar/baz ``` in the address bar of chromium? If a capture is sent to emacs, then something is screwy with the extension - let me know.

Otherwise, something made chromium broke the org-protocol:// association to emacsclient (perhaps a newly installed DE / OS version), and you should probably follow http://orgmode.org/worg/org-contrib/org-protocol.html#sec-3-1 in setting it up again (also let me know :-).

**Comment by sprig** [comment]
I am closing the issue. If the previous comment hasn't solved your problem, feel free to reopen it.
