### ISSUE TITLE
Broken with last org-mode version

### ISSUE THREAD

**Issue by freddez** [sprig/org-capture-extension#60]
Hello, the extension is broken (tested with Firefox and Chrome), probably related to an org-mode update. Links are inserted like that in org file, with strange escape characters:

[[https%253A%252F%252Fgithub.com%252Fsprig%252Forg-capture-extension][sprig%2Forg-capture-extension%3A%20A%20Chrome%20and%20firefox%20extension%20facilitating%20org-capture%20in%20emacs]]

**Comment by wdwhy** [comment]
Also facing this issue since upgrade to org 9.2.2. As per [this](https://www.reddit.com/r/orgmode/comments/ayjfl3/org_update_to_922_url_encodes_orgcapture/ei1baqj) reddit post it appears it might be related to the changes discussed here: https://lists.gnu.org/archive/html/emacs-orgmode/2019-02/msg00320.html

**Comment by sprig** [comment]
Sorry, I'm not sure what exactly is "broken". What do you expect to happen, and what happens instead? What versions are you using? What's your capture template? There is a guide to filing a bug report in the readme.

Not sure I completely understand the issue but skimming through @wdwhy's link, it appears as though this may be by design of org-mode 9.2.2. Perhaps yet a new capture mode is necessary, although I'm not sure what's the bottom line re escaping.

**Comment by freddez** [comment]
Oh Sorry, I've just updated org-mode  and it works now.
