### ISSUE TITLE
Chrome asking confirmation to launch EmacsClients *every time* when capturing

### ISSUE THREAD

**Issue by klapauciusisgreat** [sprig/org-capture-extension#68]
This is the latest Chrome (79.0.3945.88 (Official Build) (64-bit) ) on macOS Catalina.

Is there a way to give the extension the permission to not have to ask every time ?

**Comment by birdgg** [comment]
https://superuser.com/questions/1481851/disable-chrome-to-ask-for-confirmation-to-open-external-application-everytime

**Comment by chrisberkhout** [comment]
This can be fixed by setting an [`AutoLaunchProtocolsFromOrigins`](https://cloud.google.com/docs/chrome-enterprise/policies/?policy=AutoLaunchProtocolsFromOrigins) policy.


For example, for Chromium on Linux, create a file here:
```
/etc/chromium/policies/managed/org-protocol.json
```
with this content:
```json
{
  "AutoLaunchProtocolsFromOrigins": [
    {
      "allowed_origins": [ "*" ],
      "protocol": "org-protocol"
    }
  ]
}
```
Ensure it is read-only for non-admin users.

Relauch Chromium and check [`chrome://policy/`](chrome://policy/) to confirm that the policy is set.

For information on setting policies for other builds and platforms, read the Quick Start guides in the [Documentation for Administrators](https://www.chromium.org/administrators).

**Comment by AloisJanicek** [comment]
Here is how you do it on Windows:

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
"AutoLaunchProtocolsFromOrigins"="[{\"allowed_origins\":[\"*\"],\"protocol\":\"org-protocol\"}]"
```

save this as a `.reg` file, double-click it to install it

**Comment by bgueth1** [comment]
Thanks! How do you do this on MacOS?

**Comment by Lubricy** [comment]
> Thanks! How do you do this on MacOS?

for those who use MacOS, heres how it did the trick for me:

```shell
#!/usr/bin/env bash
defaults write com.google.Chrome AutoLaunchProtocolsFromOrigins -array '<dict>
        <key>allowed_origins</key>
        <array>
                <string>*</string>
        </array>
        <key>protocol</key>
        <string>org-protocol</string>
</dict>'
```

after that you can head over to `chrome://policy`, search for `AutoLaunchProtocolsFromOrigins`, then click on `Reload policies` to verify. 

the config seems to be stored in `~/Library/Preferences/com.google.Chrome.plist` which you can decode/read with `plutil -convert xml1` etc.

**Comment by AnabasisXu** [comment]
Thank you [AloisJanicek](https://github.com/AloisJanicek)!
For Chromium users on Windows, the following code works:

1. save this as a .reg file, double-click it to install it

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Chromium]
"AutoLaunchProtocolsFromOrigins"="[{\"allowed_origins\":[\"*\"],\"protocol\":\"org-protocol\"}]"
```

2. go to chrome://policy/, click "Reload policies", the status should be OK.




<details>
<summary>
Trial and Error
</summary>

At first, I thought the path should be like:

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Chromium\Chromium]
```
or 
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chromium]
```
</details>

**Comment by sprig** [comment]
Since instructions have been posted I will pin and close the issue for now, and consider adding something to the docs. I should warn that this might have security implications as it could allow arbitrary websites to send commands to emacs. Likely a small risk considering how custom the configuration is for each user, but nevertheless.
