### ISSUE TITLE
Pages with square brackets "[ ]" in the title fail to capture

### ISSUE THREAD

**Issue by mcg** [sprig/org-capture-extension#7]
The capture is logged in the Chrome console, but apparently never sent to emacs/org.
This page is an example: https://lists.gnu.org/archive/html/emacs-orgmode/2016-03/msg00509.html

**Comment by sprig** [comment]
The page works for me, but does break the capture template that I use, since it creates a link in the note, of the form [[<url>][<title>]], and if the title contains brackets, it screws up the link parsing by org.

What definitely does happen is the capture getting sent to emacs (here). So what I am guessing, assuming that captures from different sites work correctly for you, is that you need to work more on your capture template to make it more robust with regards to that.

If you make a nicely working capture template and wish to contribute it, I would be happy to add it as an example.

**Comment by mcg** [comment]
I've actually run into a few other pages that do not get transferred to emacs by clicking the extension. Tho if I have the developer console open and click on the logged URL, it works.

**Comment by mcg** [comment]
Further digging, the extension works reliably in incognito mode. I assumed it was another extension interfering, but after disabling all of them it still doesn't work reliably in a normal browser session. Strange.

**Comment by sprig** [comment]
Very odd indeed. I can't even imagine what could interfere. What is your platform+versions for the relevant stack?

**Comment by mcg** [comment]
Chrome 50.0.2661.49 beta (64-bit) on Ubuntu. 
I've fallen back to a bookmarklet that seems reliable.

**Comment by sprig** [comment]
Also, additional two suggestions:
1. Get the bookmark scriptlet from the org page and see if it works on affected pages
2. If it does appear to work, make the same bookmarklet, but change the url scheme from ```org-protocol:/...``` to ```org-debug-protocol:/...``` (just something I made up now). Register ```org-debug-protocol``` to some script, e.g. ```~/.local/bin/org-debug-handler``` and put into it:
``` bash
#!/bin/bash
echo "Received request at $(date)" >> ~/.org-debug-log
echo "$@" >> ~/.org-debug-log
```

Then see what is different about those pages.
Also, it may a tired old mantra, but if you are working with a beta version of the browser, expect breakage and be able to handle debugging.

Anyway, esp. due to now knowing this (and not being able to reproduce), I will reclose until further workable information.
