### ISSUE TITLE
No server buffers remain to edit

### ISSUE THREAD

**Issue by chloejooo123** [sprig/org-capture-extension#82]
Hi, I am trying to use org-capture extension to capture information online. I have managed to set up the protocol and if I don't select any text and only captures the URL link, the extension works just fine. However, whenever I tried to capture a link with selected text, I always received `No server buffers remain to edit` error in my minibuffer.

I have tried both the chrome extension and firefox extension. They work just fine the first time I installed them but will not be useable if I reopen my emacs.

Here's my configuration, I have went through many answers online but non solved my problem.

```
(defun transform-square-brackets-to-round-ones(string-to-transform)
  "Transforms [ into ( and ] into ), other chars left unchanged."
  (concat 
   (mapcar #'(lambda (c) (if (equal c ?[) ?\( (if (equal c ?]) ?\) c))) string-to-transform))
	)
```

```
(setq org-capture-templates '(("p" "Protocol" entry (file+headline "~/Notes/captures.org" "Inbox")
						"* %^{Title}\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?")	
						("L" "Protocol Link" entry (file+headline "~/Notes/captures.org" "Link")
						 "* %? [[%:link][%(transform-square-brackets-to-round-ones \"%:description\")]]\n")))
```

**Comment by Vardhamann** [comment]
im facing the same issue, any fix?

**Comment by KaizerPublications** [comment]
Hey, had the same issue. I fixed it by changing both the template and the function definition.
Here's the current config:

``
(setq org-capture-templates `(
                              ("p" "Protocol" entry(file+headline ,(concat org-directory "Roam/Captures/web_capture.org") "Inbox")
                               "* %^{Title}\n Source:  %u, %:annotation \n#+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?")
                              ("L" "Protocol Link" entry(file+headline ,(concat org-directory "Roam/Captures/web_capture.org") "Inbox")
                               "* %? [[%:link][%:description]] \n Captured On: %U")))
``

The Protocol 'p' template has issues with spacing before #+BEGIN_QUOTE and the %c copies from the kill ring and not the current position in the browser. %:annotation just places the current link. We can use %a, %l or %:annotation with the same result. I chose %:annotation because it's specific to org-protocol.

If the template is messed up, you will have issues because the command fails on the emacs side with an error message pointing to the template not being properly configured. Try without the extension to use a faulty template, the command will fail.

Removing the space before the #+BEGIN_QUOTE is just for neatness.

Note, if you copy an example that has fields that can be filled you will get a prompt. Eg: if the copied text has {TITLE} in it, you will get a prompt to replace the {TITLE} in the capture template.

The defun transform function also has an issue with unescaped characters. Change it to:

``
(defun transform-square-brackets-to-round-ones(string-to-transform)
  "Transforms [ into ( and ] into ), other chars left unchanged."
  (concat
   (mapcar #'(lambda (c) (if (equal c ?\[) ?\( (if (equal c ?\]) ?\) c))) string-to-transform)))
``

You should be fine from there.

**Comment by KaizerPublications** [comment]
Oh, I forgot to mention. You can change org-directory to whatever sub-directory you feel like. I use roam so that's where I store my stuff.

**Comment by sprig** [comment]
As commented above this looks like an issue with the template in emacs.
